### ISSUE TITLE
Is Farnell local enough to Germany? 

### ISSUE THREAD

**Issue by kasbah** [amchagas/local_suppliers#2]
All the products ordered from *.farnell.com sub-domains are served by stocks held in the UK and Belgium (Liege) I believe. Maybe it's still local enough to order to Germany though? Maybe it'll arrive quickly enough to do a workshop? I guess the real question is: what's the criteria for "local"?

**Comment by amchagas** [comment]
I guess the criteria for "local" is quite undefined. But when ordering things from farnell in Germany specifically, we can get them 1-2days later using regular shipping. Enough for a workshop :)
As I mentioned on issue #3 , I think most inclusions are valid, as long as we make an observation to clarify points that might be problematic

**Comment by kasbah** [comment]
Makes sense, fair enough. Might be worth putting the criteria in the readme.
